# Generated by Django 5.0 on 2024-02-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField()),
                ('emp_name', models.CharField(max_length=1000)),
                ('emp_address_temporary', models.CharField(max_length=1000)),
                ('emp_address_permanent', models.CharField(max_length=1000)),
                ('emp_date_of_birth', models.DateField(blank=True, null=True)),
                ('emp_email', models.EmailField(max_length=1000)),
                ('emp_contact_number', models.PositiveBigIntegerField()),
            ],
        ),
    ]
