# Generated by Django 5.0 on 2024-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_national',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_contact_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='default value', max_length=1000),
        ),
    ]
