# Generated by Django 5.0 on 2024-02-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_employee_emp_national_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_national',
            field=models.CharField(max_length=1000, null=True, blank=True),
        ),
    ]
