# Generated by Django 5.0 on 2024-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_alter_employee_emp_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(default='blank-profile-picture-973460_960_720.webp', upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_national',
            field=models.CharField(default='default_value', max_length=1000),
        ),
    ]
