# Generated by Django 5.0 on 2024-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_employee_emp_image_alter_employee_emp_national'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_primary', models.CharField(max_length=1000)),
                ('work_secondary', models.CharField(max_length=1000)),
                ('work_primary_image_stufa', models.ImageField(upload_to='image/')),
                ('work_secondary_image_field', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(default='blank-avatar-photo-icon-design-vector-30257190.jpg', upload_to='image/'),
        ),
    ]
