# Generated by Django 5.0 on 2024-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_work_alter_employee_emp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_primary_description',
            field=models.CharField(blank=True, default='default_value', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='work_secondary_description',
            field=models.CharField(blank=True, default='default_value', max_length=1000, null=True),
        ),
    ]
